Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |vb|
	vb.memory = "1024"
	vb.cpus = 2
  end
  config.vm.network "forwarded_port", guest: 80, host: 8081
  config.vm.hostname = "vagrant-otus"
  config.vm.disk :disk, size: "1GB", name: "disk1"
  config.vm.disk :disk, size: "1GB", name: "disk2"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    disk1=$(lsblk -d -n -o NAME,SIZE | grep 1G | awk '{print $1}' | sed -n '1p')
    disk2=$(lsblk -d -n -o NAME,SIZE | grep 1G | awk '{print $1}' | sed -n '2p')
    mkfs.ext4 -F /dev/$disk1
	mkfs.ext4 -F /dev/$disk2
	mkdir /mnt/disk1 /mnt/disk2
	UUID1=$(lsblk -o NAME,UUID | grep $disk1 | awk '{print $2}')
	UUID2=$(lsblk -o NAME,UUID | grep $disk2 | awk '{print $2}')
	echo "UUID=$UUID1  /mnt/disk1 ext4  defaults,nofail  0  2" >> /etc/fstab
	echo "UUID=$UUID2  /mnt/disk2 ext4  defaults,nofail  0  2" >> /etc/fstab
	mount -a
   SHELL
end
